spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/air
    username: air
    driver-class-name: org.postgresql.Driver
    password: air
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
