spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uxarairline
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: redd
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
