server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true #Разрешает гейтвею автаматически определять маршруты до сервисов
        lowerCaseServiceId: true