spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    lease-expiration-duration-in-seconds: 999 # Время через которое сервер удалит экземпляр клиента, если клиент не будет слать информацию о себе.
    hostname: localhost
  client:
    registerWithEureka: false # Указывает, должен ли этот экземпляр регистрировать свою информацию на сервере eureka для обнаружения другими.
    fetchRegistry: false # Получать или нет информацию о зарегистрированных клиентах.
    eureka-service-url-poll-interval-seconds: 10 # Как часто (в секундах) запрашивать изменения в информации
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka

