spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_db
    username: postgres
    password: root
  #  liquibase:
  #    change-log: classpath:db.changelog-master.xml;
  #    url: jdbc:postgresql://localhost:5432/airline_db
  #    user: postgres
  #    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
  main:
    allow-circular-references: true


jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==