#datasourse?

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/airline_db
    username: postgres
    password: root
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml



