#server:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: non
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    ROOT: INFO
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/